// src/components/backlog/mockData.ts
import { BacklogItemType } from "@/types";

export const getExampleData = (projectId: string): BacklogItemType[] => [
  {
    id: "1",
    projectID: projectId,
    parentId: null,
    type: "epic",
    name: `Épica 1 Larga Con Mucho Texto Que Debería Truncarse Correctamente`,
    description: "Descripción épica 1",
    status: "backlog",
    priority: "highest",
    createdAt: new Date(2023, 0, 1).toISOString(),
    updatedAt: new Date().toISOString(),
    size: 8,
  },
  {
    id: "2",
    projectID: projectId,
    parentId: "1",
    type: "story",
    name: `Historia 1.1`,
    description: "Descripción historia 1",
    status: "inprogress",
    priority: "high",
    createdAt: new Date(2023, 1, 1).toISOString(),
    updatedAt: new Date().toISOString(),
    size: 5,
  },
  {
    id: "3",
    projectID: projectId,
    parentId: "1",
    type: "story",
    name: `Historia 1.2`,
    description: "Descripción historia 2",
    status: "todo",
    priority: "medium",
    createdAt: new Date(2023, 1, 15).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    projectID: projectId,
    parentId: "3",
    type: "task",
    name: `Tarea 1.2.1`,
    description: "Subtarea",
    status: "backlog",
    priority: "low",
    createdAt: new Date(2023, 2, 1).toISOString(),
    updatedAt: new Date().toISOString(),
    size: 1,
  },
  {
    id: "5",
    projectID: projectId,
    parentId: "3",
    type: "bug",
    name: `Bug 1.2.2`,
    description: "Un bug encontrado",
    status: "blocked",
    priority: "high",
    createdAt: new Date(2023, 2, 5).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    projectID: projectId,
    parentId: null,
    type: "epic",
    name: `Épica 2`,
    description: "Descripción épica 2",
    status: "done",
    priority: "lowest",
    createdAt: new Date(2023, 0, 10).toISOString(),
    updatedAt: new Date().toISOString(),
    size: 13,
  },
];
